services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dev
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    volumes:
      - /opt/mariadb/data:/var/lib/mysql
    ports:
      - "10001:3306"
    restart: unless-stopped
    networks:
      docker_tools:
        ipv4_address: 172.20.0.2

  adminer-mariadb:
    image: adminer:latest
    container_name: adminer-mariadb
    ports:
      - "10002:8080"
    restart: unless-stopped
    depends_on:
      - mariadb
    networks:
      docker_tools:
        ipv4_address: 172.20.0.3

  postgresql:
    image: postgres:latest
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dev
    volumes:
      - /opt/postgresql/data:/var/lib/postgresql/data
    ports:
      - "10003:5432"
    restart: unless-stopped
    networks:
      docker_tools:
        ipv4_address: 172.20.0.4

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "10004:80"
    restart: unless-stopped
    depends_on:
      - postgresql
    networks:
      docker_tools:
        ipv4_address: 172.20.0.5

  redis:
    image: redis:latest
    container_name: redis
    volumes:
      - /opt/redis/data:/data
    ports:
      - "10005:6379"
    restart: unless-stopped
    networks:
      docker_tools:
        ipv4_address: 172.20.0.6

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      REDIS_HOSTS: redis
      REDIS_HOSTS_LOCAL_HOST: redis
      REDIS_HOSTS_LOCAL_PORT: 6379
    ports:
      - "10006:8081"
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      docker_tools:
        ipv4_address: 172.20.0.7

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /opt/mongo/data:/data/db
    ports:
      - "10007:27017"
    restart: unless-stopped
    networks:
      docker_tools:
        ipv4_address: 172.20.0.8

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongo
    ports:
      - "10008:8081"
    restart: unless-stopped
    depends_on:
      - mongo
    networks:
      docker_tools:
        ipv4_address: 172.20.0.9

  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "10009:8025"
      - "10010:1025"  # SMTP
    restart: unless-stopped
    networks:
      docker_tools:
        ipv4_address: 172.20.0.10

volumes:
  mariadb_data:
    driver: local
  postgresql_data:
    driver: local
  redis_data:
    driver: local
  mongodb_data:
    driver: local

networks:
  docker_tools:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24